### ISSUE TITLE
Build failing on master

### ISSUE THREAD

**Issue by fabiob** [pleerock/routing-controllers#265] opened 2017-08-29 14:55 UTC
I'm trying to add new tests so #167 can be merged, but the automated build is currently broken.

Is there an ETA to fix it?

**Comment by NoNameProvided** [comment] 2017-08-30 06:56
This is due to some internal changes in the latest Node version. You can add your tests and ignore that one failing tests about sessions.

Duplicate of #243

**Closed by NoNameProvided** 2017-08-30 06:56 UTC
Labels: duplicate
