### ISSUE TITLE
Session problem with default error handler

### ISSUE THREAD

**Issue by iH8c0ff33** [pleerock/routing-controllers#70] opened 2017-02-01 05:36 UTC
when using `express-session` the default error handler fails to write the request because the request is closed before any data is sent.

**Comment by 19majkel94** [comment] 2017-02-05 09:23
I use express-session with routing-controllers with no problems.
Could you provide minimal sample of code to reproduce the error? Or describe the problem in more details 😉

**Comment by iH8c0ff33** [comment] 2017-02-05 09:41
I will do that in a moment @19majkel94

**Comment by iH8c0ff33** [comment] 2017-02-05 11:17
That's my session config:
```typescript
app.use(express_session({
  secret: cookie_secret,
  // Don't store sessions that are not logged in
  saveUninitialized: true,
  resave: false,
  store: new TypeormStore({}),
  cookie: {
    maxAge: 1000 * 60 * 60 * 24 * 365,
    secure: process.env.NODE_ENV === 'production'
  },
  proxy: true
}))
```
and my routing-controllers one:
```typescript
useExpressServer(app, {
  controllers: [join(__dirname, 'controller', '*.js')],
  middlewares: [join(__dirname, 'middleware', '*.js')],
  defaultErrorHandler: false
})
```
If I enable default error handler that route, which has a required parameter, fails:
```typescript
@Post('/test')
test( @BodyParam('daw', { required: true }) daw: boolean) {
  return {
    ok: true
  }
}
```
because it sends an empty response, while setting content-length correctly, which is strange...
```http
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 65
Date: Sun, 05 Feb 2017 11:13:28 GMT
Connection: close
```
the logs are the following
```
  body-parser:json body already parsed +3ms
  express-session touching +1ms
  express-session split response +0ms
  express:router <anonymous>  : /api/v2/user/test +2ms
  finalhandler default 500 +1s
  finalhandler cannot 500 after headers sent +0ms
Parameter daw is required for request on POST /api/v2/user/test
{
  "name": "spaggiari-web-api",
  "hostname": "Danieles-MBP.station",
  "pid": 11779,
  "level": 50,
  "msg": "Parameter daw is required for request on POST /api/v2/user/test",
  "time": "2017-02-05T11:13:28.293Z",
  "v": 0
}
  express-session touched +18ms
```

**Comment by iH8c0ff33** [comment] 2017-02-08 13:32
@19majkel94 have you been able to reproduce this issue, or is it related to something wrong with my code?

**Comment by pleerock** [comment] 2017-04-03 07:43
@19majkel94 need your help because I never used sessions and have no idea how they work in express

**Comment by 19majkel94** [comment] 2017-04-03 17:28
And I have no idea what is happening here and what this issue is about 😆 

@iH8c0ff33
I would need a gist or a repo with working minimal codebase to reproduce the issue. Minimal, not copy-paste your project, just try to build it from scratch, maybe your other middleware conflict with `express-session` and the issue is not related with routing-controllers?
I would then only `git clone`, `npm install`, `npm start` and reproduce the issue without rewriting half of your app :wink:

**Comment by iH8c0ff33** [comment] 2017-04-03 19:00
@19majkel94 I'm trying to figure out which middleware causes this, but it's not that easy for me... I'll need some time

**Comment by iH8c0ff33** [comment] 2017-04-03 20:34
@19majkel94 

```typescript
            // send error content
            if (action && action.isJsonTyped) {
                response.json(this.processJsonError(error));
            } else {
                response.send(this.processTextError(error)); // todo: no need to do it because express by default does it
            }
        }
        options.next(error);
```
could that be the problem? (options.next(error) is called even if response.send was already called)

**Comment by 19majkel94** [comment] 2017-04-04 16:50
Yes and no. Sometimes you want default error handler to handle error response but you also want log some of the errors in *.log or in DB. So you create GlobalMiddlewareAfter and it's called after default error handler but you can't send anything to response, just use error and request objects. So the line must stay but it may conflict with other error handlers as you see.

**Comment by iH8c0ff33** [comment] 2017-04-04 17:12
@19majkel94 Ok, but I see the response goes into finalhandler untouched after that and then it logs "can't {error code} after headers sent" and the request isn't actually sent, but only the headers.

**Comment by pleerock** [comment] 2017-04-24 13:09
its normal `(options.next(error) is called even if response.send was already called)` because there are middlewares which can do the job after your controller actions.  @iH8c0ff33 if you are still interested in this issue please create a minimal reproduction repo for @19majkel94 to debug, or close it if you aren't anymore.

**Comment by iH8c0ff33** [comment] 2017-04-27 22:20
@19majkel94 can I send you my app as a reproduction? I really removed everything and don't know which is the problem since if I start a project with just a controller it just works, but my repo with everything but typeorm disabled doesn't work.

**Comment by pleerock** [comment] 2017-05-22 08:27
ping @19majkel94

**Comment by 19majkel94** [comment] 2017-05-22 18:28
pong 😆 
@iH8c0ff33 you can send me your app, I will try to find some time to investigate this issue.

**Comment by iH8c0ff33** [comment] 2017-05-24 13:17
@19majkel94 
I'll now send you the project as a zip file, but let me firstly explain what exactly the problem is:
The first time i make a request with missing parameter (expecting a 400 error) i get the error correctly sent in the response:
```http
HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
X-Served-By: MacBook-Pro.local
Content-Type: application/json; charset=utf-8
Content-Length: 1596
set-cookie: connect.sid=s%3AyYCEaleOH2LruRaUb46gX0roQI404tHA.8Q1UqcEk45%2BkX5MekEG0ZHCmu3Fj%2Fx0S6nvgHJgRQNU; Path=/; Expires=Thu, 24 May 2018 12:42:00 GMT; HttpOnly
Date: Wed, 24 May 2017 12:42:00 GMT
Connection: close

{"name":"ParamRequiredError","message":"Parameter is required for request on POST /api/v2/user/login","stack":"Error\n    at ParamRequiredError.HttpError [as constructor] (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at ParamRequiredError.BadRequestError [as constructor] (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/http-error/BadRequestError.js:20:28)\n    at new ParamRequiredError (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/error/ParamRequiredError.js:20:28)\n    at ActionParameterHandler.handleValue (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/ActionParameterHandler.js:78:39)\n    at ActionParameterHandler.handle (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/ActionParameterHandler.js:39:21)\n    at /Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/RoutingControllers.js:87:67\n    at Array.map (native)\n    at RoutingControllers.executeAction (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/RoutingControllers.js:87:14)\n    at /Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/RoutingControllers.js:56:34\n    at routeHandler (/Users/daniele/Documents/workspaces/nodejs/spaggiari-web-api/node_modules/routing-controllers/driver/express/ExpressDriver.js:134:20)"}
```
But the second time, when the session is already in the database, it fails (that thing made me think about an express-session issue) because the response body will not be sent:
```http
HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
X-Served-By: MacBook-Pro.local
Content-Type: application/json; charset=utf-8
Content-Length: 1596
Date: Wed, 24 May 2017 12:44:18 GMT
Connection: close
```
It must be something with express-session I think... but I really can't understart where's the problem...
Here is the app's zip file.
[myApp.zip](https://github.com/pleerock/routing-controllers/files/1025605/myApp.zip)

**Comment by pleerock** [comment] 2017-05-25 07:44
OMG we are using git and github and we still attach zip files... 😖

**Comment by 19majkel94** [comment] 2017-09-05 16:14
Ok, I think that the issue problem is that we call `next(error)` even after handling error and the express-session middleware is trying to handle the error. So I'm closing the issue as it's related to #144 #256.

For now the workaround is creating own error middleware that doesn't bubble the error and disabling the default one.

**Closed by 19majkel94** 2017-09-05 16:14 UTC
Labels: needs more info
