### ISSUE TITLE
Error thrown when classTransformer is enabled (by default) for plain objects

### ISSUE THREAD

**Issue by snirs90** [pleerock/routing-controllers#195] opened 2017-06-30 07:44 UTC
I have a route defined this way:

```
@Get("/google/oauthcallback")
async oAuthCallback(@QueryParam("code") code: string) {
        return { exists: true };
}
```

and it's throwing me an error:
```
TypeError: Cannot read property 'prototype' of undefined
    at /private/var/www/server/node_modules/class-transformer/metadata/MetadataStorage.js:131:84
```

Only If I define a real "class" and then return it, it works, for example:

```
async oAuthCallback(@QueryParam("code") code: string) {
  class User {}
  const user = new User();
  return user;
}

```

The response will be: ```{ }```

The expected behavior is to work on plain objects also (and expose the needed fields if has been set)
In this case, there is even no use of a decorator or method to transform a class or expose specific fields..

Thanks,

**Comment by snirs90** [comment] 2017-07-02 16:35
So after deep debugging I found out it's not routing-controller issue.
It is `class-transformer` library issue.

I had this annotation on some model
```
@ManyToOne(type => User, 'id', { nullable: false })
    @Expose({ groups: ['message.create'] })
    @Transform(data => {
        if (!isNaN(data)) {
            const obj = plainToClass(User, { id: data }, { groups: ['user.transform.id'] });
            return obj;
        }
        return data;
    }, { toClassOnly: true })
    user_id: User;
```

The problem is with the ```@Transform``` annotation, what I'm trying to do there is when I'm populate the user_id field with a user id number, it should transform it to a User Object so I can insert it to the typeorm.

Not sure this is the correct way - @pleerock can you take a look at say your opinion?
Anyway, why it's throwing an error if I'm not using this model in the specific controller? the code of this model shouldn't be executed..

Anyway this issue is not related to the routing-controller library.

Thanks!

**Comment by pleerock** [comment] 2017-07-04 08:51
if you remove `@Transform` decorator - does it work?

**Comment by G-Ray** [comment] 2017-07-04 13:31
Same error when trying to @Transform a simple string:
```
@Transform(value => hideValue(value), { toPlainOnly: true })
firstname: string;
```

**Comment by 19majkel94** [comment] 2017-08-07 15:54
Cannot reproduce the issue on the newest version of `routing-controllers`:
```ts
import { Get, JsonController, createKoaServer, createExpressServer } from "routing-controllers";

@JsonController()
class GithubController {
    @Get("/plain")
    returnPlainObject() {
        return {
            message: "test",
            number: 12,
        }
    }
}

createExpressServer().listen(3001, () => {
    console.log("express on")
})

createKoaServer().listen(3002, () => {
    console.log("koa on")
})
```
@snirs90 Can you confirm still exist? Or returning plain objects is not a case of the issue?

**Comment by 19majkel94** [comment] 2017-08-31 19:53
Closing as cannot reproduce & no info from the issue author.

**Closed by 19majkel94** 2017-08-31 19:53 UTC
Labels: needs more info
