### ISSUE TITLE
Using class-transformer reduces routes performance

### ISSUE THREAD

**Issue by ssljivic** [pleerock/routing-controllers#153] opened 2017-05-21 19:09 UTC
Hi @pleerock 

It looks like there is huge performance penalty when using routing controllers, which is too bad since I really like this library. Can you please take a look at the below example?

I forked your routing-controllers-express-demo and added another endpoint to demonstrate the performance issue. Please find the fork here: https://github.com/ssljivic/routing-controllers-express-demo

Perform GET on the following 2 endpoints:

- http://localhost:3000/posts
- http://localhost:3000/posts2

Second endpoint writes the same array of posts directly to the response using res.send().

In my test environment, first endpoint takes **380 ms**, while the second one takes **20 ms**.

**Comment by alexproca** [comment] 2017-05-21 19:21
Hi @ssljivic !

I had a similar perfomance problem with mongoose objects. And beside that they get serialized as as a whole mongoose objects instead of just JSON representation. I implemented the following workaround:

``` typescript
import { InterceptorGlobal, InterceptorInterface } from 'routing-controllers';

@InterceptorGlobal()
export class ConvertMongoose implements InterceptorInterface{

    intercept(req, res, result) {
        res.send(result);
    }
}
```

**Comment by ssljivic** [comment] 2017-05-21 19:51
@alexproca in the example above I did not use Mongoose objects - just simple objects with few properties.

The interceptor you used would probably help, but it would be better to fix the root issue.

**Comment by alexproca** [comment] 2017-05-21 20:49
Sure it would be better to fix it.

Of course I have seen you didn't use mongoose objects 😄 but you observed the library serialization is slower than express `res.send()` and I had a problem too with default serialization (it did not serialize mongoose objects as I expected) so I suggested a workaround that replaces the default serialization. This will help until the issue is solved.

**Comment by pleerock** [comment] 2017-05-22 04:37
mongoose objects is a pain IMHO. @alexproca you could simply disable default serialization, there is an option for this.

@ssljivic can you please help and make a debug and try to find what is exactly slow? Also try to change:
```ts
 @Get("/posts2")
    all2(@Res() res: any): Promise<void> {
        return this.postRepository.findAll()
        .then(posts => {
            res.send(posts);
        });
    }
```

to

```
 @Get("/posts2")
    all2(@Res() res: any): Promise<void> {
        this.postRepository.findAll()
        .then(posts => {
            res.send(posts);
        });
    }
```

(no return).

Right now this sounds like a serializer issue, try to set `useClassTransformer: false` in routing-controllers [options](https://github.com/pleerock/routing-controllers#creating-instances-of-classes-from-action-params). 380ms vs 20ms sounds quite bad, so we need to fix this.

**Comment by ssljivic** [comment] 2017-05-22 06:52
@pleerock I can confirm that with `useClassTransformer: false` the time is **20 ms**.

**Comment by alexproca** [comment] 2017-05-22 11:42
You are right @pleerock mongoose objects are a pain but I have to stick with them for a while.

( maybe I will migrate to [typeodm](https://github.com/pleerock/typeodm) in the future 😄 - It would be nice for typeodm to enable other nosql backends too )

Thanks for the tip. I disabled default class transformer with `useClassTransformer: false` and removed `@InterceptorGlobal`

**Comment by ssljivic** [comment] 2017-05-25 17:57
@pleerock do you think that this performanace issue can be resolved in class-transformer project? 

Maybe, for a start, we can split `useClassTransformer` into 2 new config options: `useRequestClassTransformer` and `useResponseClassTransformer`. Right now setting the `useClassTransformer = false` is not an option as request will not be transformed.

**Comment by pleerock** [comment] 2017-05-26 05:33
> @pleerock do you think that this performanace issue can be resolved in class-transformer project?

we totally should. However at the moment my focus is mostly on typeorm and future typestack projects. I need some help on other libs from community.

**Comment by pleerock** [comment] 2017-06-27 13:52
@ssljivic can you please check it with the latest class-transformer `0.1.7` version?

**Comment by ssljivic** [comment] 2017-07-01 10:59
@pleerock with class-transformer 0.1.7 it is about 7 times faster than with previous 0.1.6 version. That is great increase in speed 👍 🥇 .

However, it is still 2 times slower than the res.send(). Although 0.1.7 provides tremendous speed improvement, it would still be a good to have an option to disable class transformer for responses, both as a global cfg and on per controller and/or method level.

**Comment by NoNameProvided** [comment] 2017-08-08 14:24
As #226 has a broader conversation about the topic I will close this as a duplicate.
Please subscribe to #226 to be notified when the required changes land. Thanks.

**Closed by NoNameProvided** 2017-08-08 14:24 UTC
Labels: duplicate
