### ISSUE TITLE
Returning undefined in a JsonController does not return JSON.

### ISSUE THREAD

**Issue by GeeWee** [pleerock/routing-controllers#231] opened 2017-08-01 07:37 UTC
A JSONController that returns undefined, returns a 404, but with the content type set to html, and a html document with the error message.

Simple repro:

```
@JsonController('/widget')
export class WidgetController {
	@Get('/:id')
	public async getOne(@Param('id') id: number) {
		return undefined;
	}
}
```

and a test using supertest
```
const response = await request(app)
			.get('widget/1')
			.expect('Content-Type', /json/)
```

I think it would make more sense for the error to be returned in json format.

**Comment by 19majkel94** [comment] 2017-08-06 10:49
The problem is here:
https://github.com/pleerock/routing-controllers/blob/master/src/driver/express/ExpressDriver.ts#L279
And in koa driver too!

`undefined` goes throught whole `if-else` tree and goes up to the last `else` statement which call `next()`. So it behaves like there were no registered route and the response shape depends on how the underlying framework handle it.

And you're right, this shouldn't work like this, I will try to fix it now 😉

**Comment by GeeWee** [comment] 2017-08-06 13:37
Wonderful!

**Comment by pleerock** [comment] 2017-09-04 10:40
since PR is merged I think this can be closed

**Closed by pleerock** 2017-09-04 10:40 UTC
Labels: bug
