### ISSUE TITLE
when i query a resource, i wish a bson convert to a string, not to this...

### ISSUE THREAD

**Issue by HiLittleCat** [pleerock/routing-controllers#296] opened 2017-09-21 02:03 UTC
"_id":{"_bsontype":"ObjectID","id":{"0":89,"1":195,"2":26,"3":205,"4":69,"5":86,"6":70,"7":7,"8":45,"9":238,"10":232,"11":134}}

**Comment by 19majkel94** [comment] 2017-09-21 08:59
Closing as kinda duplicate of #226 - the issue with class-transformer and mongo documents. Use `@Transform` to convert it manually or call `toJson()` or sth.

**Closed by 19majkel94** 2017-09-21 08:59 UTC
Labels: duplicate
