### ISSUE TITLE
@UploadedFile and @Body

### ISSUE THREAD

**Issue by ssljivic** [pleerock/routing-controllers#150] opened 2017-05-19 14:21 UTC
Is it possible and how to combine @UploadedFile and @Body in the same endpoint? 

From what I tested, @UploadedFile and @BodyParam works fine, but with @UploadedFile and @Body the error: 

"ParameterParseJsonError: Given parameter undefined is invalid. Value ({"foo":"123456","bar":"123456"}) cannot be parsed to JSON'".

**Comment by pleerock** [comment] 2017-05-22 04:46
`ParameterParseJsonError` thrown then given parameter value (body value) cannot be parsed into json. 

```ts
protected parseValue(value: any, paramMetadata: ParamMetadata): any {
        if (typeof value === "string") {
            try {
                return JSON.parse(value);
            } catch (error) {
                throw new ParameterParseJsonError(paramMetadata.name, value);
            }
        }

        return value;
    }
```

See [here](https://github.com/PLEEROCK/routing-controllers/blob/c9e28df9b666b63d6970bedbb73d735ff3036d47/src/ActionParameterHandler.ts#L141-L141). Try to debug and console.log value of `value` variable and why `JSON.parse` cannot handle it.

**Comment by ssljivic** [comment] 2017-05-22 09:39
@pleerock the value is already an object, so JSON.parse() is not invoked at all. However, the root exception is in the `class-validator\metadata\MetadataStorage`:

```
if (metadata.target instanceof Function &&
                !(targetConstructor.prototype instanceof metadata.target))
```

because **targetConstructor** is **undefined**.

**Comment by stonecold123** [comment] 2017-05-30 12:20
I have a similar error. Since 7.0, I cannot upload files via multer and access the `body()` object. I'm getting 
````
TypeError: Cannot read property 'prototype' of undefined
    at /home/user/project/watch/web/src/metadata/MetadataStorage.ts:79:36
    at Array.filter (native)
    at MetadataStorage.getTargetValidationMetadatas (/home/user/project/watch/web/src/metadata/MetadataStorage.ts:75:61)
    at ValidationExecutor.execute (/home/user/project/watch/web/src/validation/ValidationExecutor.ts:44:54)
    at Validator.coreValidate (/home/user/project/watch/web/src/validation/Validator.ts:31:18)
    at Validator.<anonymous> (/home/user/project/watch/web/src/validation/Validator.ts:73:35)
    at step (/home/user/project/watch/web/node_modules/class-validator/validation/Validator.js:32:23)
    at Object.next (/home/user/project/watch/web/node_modules/class-validator/validation/Validator.js:13:53)
    at /home/user/project/watch/web/node_modules/class-validator/validation/Validator.js:7:71
    at __awaiter (/home/user/project/watch/web/node_modules/class-validator/validation/Validator.js:3:12)
    at Validator.validateOrReject (/home/user/project/watch/web/node_modules/class-validator/validation/Validator.js:75:16)
    at Object.validateOrReject (/home/user/project/watch/web/src/index.ts:71:44)
    at ActionParameterHandler.validateValue (/home/user/project/watch/web/src/ActionParameterHandler.ts:175:20)
    at ActionParameterHandler.normalizeParamValue (/home/user/project/watch/web/src/ActionParameterHandler.ts:132:34)
    at ActionParameterHandler.handle (/home/user/project/watch/web/src/ActionParameterHandler.ts:44:28)
    at /home/user/project/watch/web/src/RoutingControllers.ts:116:49
    at Array.map (native)
    at RoutingControllers.executeAction (/home/user/project/watch/web/src/RoutingControllers.ts:116:14)
    at /home/user/project/watch/web/src/RoutingControllers.ts:82:33
    at routeHandler (/home/user/project/watch/web/src/driver/express/ExpressDriver.ts:143:20)
    at Layer.handle [as handle_request] (/home/user/project/watch/web/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/project/watch/web/node_modules/express/lib/router/route.js:131:13)
````

I got to use `BodyParam('json')` to access the post body.

**Comment by pleerock** [comment] 2017-06-01 09:27
I can't say from your logs that you are using latest routing-controllers version. There is no `MetadataStorage` class in the library.

**Comment by 19majkel94** [comment] 2017-06-05 09:18
> I got to use BodyParam('json') to access the post body.
Because it's how you should handle it. multipart/form-data works as an array of key-value, you can't just send file and json as a normal body, you have to put the file under the key and the json value as an another key. What should `@Body()` return when you send file and json? Can you show me the example in pure express where you send file and json and you've got all of this parsed in req.body?

**Comment by ruiming** [comment] 2017-06-07 11:18
I have the same problem as stonecold123.
Below code throw the exactly same error.
```js
export class Query {
  @IsInt() offset: number
  @IsInt() limit: number
  @IsString() sortby: string
  @IsString() order: string
}

@Controller('/v1/problems')
export class PostsController {
  @Get('/')
  async index (@Ctx() ctx: Context, @QueryParams() query: Query) {
    const problems = await ctx.services.problems.list(query.offset, query.limit, query.sortby, query.order)
    ctx.ok(problems)
  }
}
```

```
TypeError: Cannot read property 'prototype' of undefined
       at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/metadata/MetadataStorage.ts:79:36
       at Array.filter (native)
       at MetadataStorage.getTargetValidationMetadatas (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/metadata/MetadataStorage.ts:75:61)
       at ValidationExecutor.execute (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/ValidationExecutor.ts:44:54)
       at Validator.coreValidate (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/Validator.ts:31:18)
       at Validator.<anonymous> (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/validation/Validator.ts:73:35)
       at step (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/class-validator/validation/Validator.js:32:23)
       at Object.next (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/class-validator/validation/Validator.js:13:53)
       at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/class-validator/validation/Validator.js:7:71
       at Promise (<anonymous>)
       at __awaiter (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/class-validator/validation/Validator.js:3:12)
       at Validator.validateOrReject (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/class-validator/validation/Validator.js:75:16)
       at Object.validateOrReject (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/index.ts:71:44)
       at ActionParameterHandler.validateValue (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/ActionParameterHandler.ts:175:20)
       at ActionParameterHandler.normalizeParamValue (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/ActionParameterHandler.ts:132:34)
       at ActionParameterHandler.handle (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/ActionParameterHandler.ts:44:28)
       at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/RoutingControllers.ts:116:49
       at Array.map (native)
       at RoutingControllers.executeAction (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/RoutingControllers.ts:116:14)
       at /home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/RoutingControllers.ts:82:33
       at routeHandler (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/src/driver/koa/KoaDriver.ts:123:20)
       at dispatch (/home/ruiming/Documents/onlinejudge/onlineJudge-backend/node_modules/koa-compose/index.js:44:32) }
setting status code:  400
```
Is there any wrong of my code?
My enviroment:
npm: 5.0.2
node: 8.0.0
ts-target: es6

**Comment by 19majkel94** [comment] 2017-08-07 17:30
@ruiming
Your problem is currently covered with issue #227.

@ssljivic 
I'm closing the issue as it's working as intended. `multipart/form-data` can be handled only by `@BodyParam` and `@UploadedFile` combo.

**Closed by 19majkel94** 2017-08-07 17:30 UTC
Labels: help wanted

**Comment by nguyentrunghieu3010** [comment] 2018-08-12 03:30
fhdfh
