### ISSUE TITLE
async action with Authorized return 404

### ISSUE THREAD

**Issue by yaoyel** [pleerock/routing-controllers#262] opened 2017-08-24 08:53 UTC
async action with Authorized return 404

**Comment by yaoyel** [comment] 2017-08-24 08:54
async action with Authorized return 404 where server is koa
express is ok

**Comment by 19majkel94** [comment] 2017-08-24 10:12
Closing as a duplicate of https://github.com/pleerock/routing-controllers/issues/240.

**Closed by 19majkel94** 2017-08-24 10:12 UTC

**Comment by xujif** [comment] 2017-09-08 08:57
this bug still exists at 0.7.2

**Comment by 19majkel94** [comment] 2017-09-08 09:06
I've checked this:
https://github.com/pleerock/routing-controllers/issues/240#issuecomment-320595832
And it fails on 0.7.1 but works on 0.7.2. 

@xujif 
Please open a new issue if you claim that is not fixed. Create a minimal reproducible use case.

**Comment by xujif** [comment] 2017-09-08 10:11
#282
