### ISSUE TITLE
How to prevent process the  request multitime if both routes match

### ISSUE THREAD

**Issue by huanghjb** [pleerock/routing-controllers#304] opened 2017-10-09 02:14 UTC
I have two url routing ,
1.  
@Get("posts/news")  
    news(){}
2. 
@Get("posts/:id")
     byId()
both function will entered if the request url  is "posts/news", I just want news  is called

**Comment by NoNameProvided** [comment] 2017-10-09 04:59
Duplicate of #213.

Routing controllers will match both routes because your `items/:itemId` route will match alphanumeric characters and `all` is alphanumeric. What you want is to change it to `@Get('items/:itemId([0-9]+)')` to explicitly expect numerical ids. 

So it would look like: 

```ts
@JsonController()
export class ItemController {

  @Get('items/:itemId([0-9]+)')
  getItem(@Param("itemId") itemId: number) {
      log.info("/items/:itemId")
      return {message: "/items/:itemId"};
  }

  @Get('/items/all')
  getAllItems() {
      log.info("/items/all")
      return {message: "/items/all"};
  }
}
```

**Closed by NoNameProvided** 2017-10-09 04:59 UTC
Labels: duplicate

**Comment by huanghjb** [comment] 2017-10-09 06:05
but I have the case below,
```
app.post('/channel/a', func)
app.post('/channel/:others', func)
```
in express router , I just put it in order and works ok.
but in routing-controllers，
as you say ,I should do like this
```
@Get(/channel/:others(^(?!a)$))      
```
but the regexp not work, any ideas ?

**Comment by NoNameProvided** [comment] 2017-10-09 07:05
Yes, you have to exclude the `/channel/a` route, because routing-controller will trigger all matched route handler.

**Comment by huanghjb** [comment] 2017-10-09 07:17
I use the regexp below
```
@Get(/channel/:others((?!a)[0-9a-z]+)
func(@Param('others') others:string){
}
```
"/channel/a" is excluded , 
but when "/channel/b" is called , it throws the error : Parameter \"others\" is required for request on GET "/channel/b".
Param decoractor not works?

**Comment by 19majkel94** [comment] 2017-10-09 17:29
@NoNameProvided 
We really should fix it but as it will stop after middlewares working, we should discuss new API for middlewares-like thing with enhanced interceptors. So one big breaking change that fix all the issues 😃

**Comment by danghung-dev** [comment] 2019-04-14 07:10
Do you have a plan to fix it?
